### ISSUE TITLE
fails testNoMediaInTray() and testOpenPaperTray()

### ISSUE THREAD

**Issue by rskak1** [google/cloudprint_logocert#134]
Our printer fails testNoMediaInTray() and testOpenPaperTray().
Setting the type of InputTrayUnit to 'CUSTOM' results in failed
Setting the type of InputTrayUnit to 'INPUT_TRAY' results in passed.
I think this test case is supposed to fail with the setting of the type of InputTrayUnit。

**Comment by lrbom** [comment]
Can you please clarify what you mean by "setting the type of InputTrayUnit"?

**Comment by rskak1** [comment]
The meaning of "setting the type of InputTrayUnit" is the setting in CDD.
The setting is as follows.
 "input_tray_unit": [{"vendor_id": "manual","custom_display_name_localized": [{"locale": "EN",
"value": "Bypass Tray" }],"type": "CUSTOM"},{"vendor_id": "tray1","custom_display_name_localized": [
{"locale": "EN","value": "Tray 1"}],
"type": "CUSTOM"}],

In google cloud print , it is displayed as follows.
![tray](https://user-images.githubusercontent.com/20335732/28446037-2394cd16-6e03-11e7-9f1a-6648bb958dee.png)

**Comment by lrbom** [comment]
I see.
Can you please provide the log message of the 2 test failures? I am wondering if the tool is failing to detect the error message of if the error message is incorrect.

Thanks,
Kevin

**Comment by rskak1** [comment]
The log message of testOpenPaperTray() is below

LogoCert INFO: Test ID: 09f3f838-922b-4526-b5b8-bd83806816d0
LogoCert INFO: Result: Failed
LogoCert INFO: Name: Printer.OpenPaperTray
LogoCert INFO: Notes: required keyword(s) "input/tray/cassette" not in UI state message:  is open

The log message is not output in testNoMediaInTray().
The following is output to the console.
===================================================================
ERROR: testNoMediaInTray (__main__.PrinterState)

===================================================================
Verify no media in paper tray reported correctly.

----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\cloudprint_logocert-master\testcert.py", line 3351, in testN
oMediaInTray
    suffixes=('is empty')):
  File "C:\Python27\cloudprint_logocert-master\testcert.py", line 3300, in Verif
yUiStateMessage
    (keywords, _device.cdd['uiState']['caption']))
KeyError: 'caption'
----------------------------------------------------------------------
The contents of uiState when testOpenPaperTray() is below.
"uiState": {"summary": "IDLE","severity": "MEDIUM","printer": {
"vendor_item": [{"severity": "NONE","message": ""}],"output_bin_item": [{"severity": "NONE","message": " is 0% full","level_percent": 0}],"input_tray_item": [{"severity": "NONE","message": " is 100% full",
"level_percent": 100},{"severity": "MEDIUM","message": " is open"}],"marker_item": [{"severity": "NONE",
"color": "BLACK","message": "Black toner level is 100%","level_percent": 100}]},"caption": " isopen","num_issues": 1},

The contents of uiState when testNoMediaInTray() is below.
"uiState": {"summary": "IDLE","severity": "LOW","printer": {"vendor_item": [{"severity": "NONE","message": ""}],"output_bin_item": [{"severity": "NONE","message": " is 0% full","level_percent": 0}],"input_tray_item": [
{"severity": "LOW","message": " is empty"},{"severity": "LOW","message": " is empty"}],
"marker_item": [{"severity": "NONE","color": "BLACK","message": "Black toner level is 100%","level_percent": 100}]},"num_issues": 2},

**Comment by lrbom** [comment]
Hi,

Thanks for providing me with the log messages and sorry for taking some time to get back to you!
I've pushed a fix which should get rid of the " KeyError:'caption' " issue.

As for the failing test cases:

-  testOpenPaperTray():
Since the "caption" field exists in the uiState object, it is used for verification instead of the individual error messages. However, the caption value does not contain any of the necessary keywords in "input" , "tray", or "cassette". This should be fixed on the printer side.

- testNoMediaInTray():
Same issue here but for the individual error message fields, they should also the keywords. 

Please let me know if anything is unclear.

Thanks,
Kevin

**Comment by rskak1** [comment]
I think that it is not a problem on the printer side that the caption value does not contain keywords necessary for "input", "tray", or "cassette".

Whether the caption value contains keywords necessary for "input", "tray", or "cassette" depends on the type setting of input_tray_unit of CDD.
If set to a value other than CUSTOM (eg INPUT_TRAY), it is included in the caption value.
When set to CUSTOM, it is not included in the caption value.
Since setting up CUSTOM is permitted by specifications, I think that it is a matter of response content from Google server.

Type setting is "CUSTOM", the caption value from the server is "is open" .
Type setting is "INPUT_TRAY", the caption value from the server is "Input tray is open".
Type setting is "BYPASS_TRAY", the caption value from the server is "Bypass tray is open".
Type setting is "MANUAL_FEED_TRAY", the caption value from the server is "Manual feed tray is open".
Type setting is "LCT", the caption value from the server is "Large capacity tray is open".
Type setting is "ENVELOPE_TRAY", the caption value from the server is "Envelope tray is open".
Type setting is "ROLL", the caption value from the server is "Roll is open".

If set to CUSTOM and ROLL, the result of testOpenPaperTray() will fail.

**Comment by lrbom** [comment]
After speaking with the server side developers, they have agreed that this is a bug and will be looking into this. I will let you know when this is resolved. Until then, please ignore the failures for the 2 testcases that we discussed for your printer.
